apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubeutils.fullname" . }}-web
  labels:
    app.kubernetes.io/component	: web
    {{- include "kubeutils.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/component	: web
    {{- include "kubeutils.labels" . | nindent 4 }}
  type: ClusterIP
  ports:
  - port: 80