kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "ibmdb2.fullname" . }}-server
  labels:
    app.kubernetes.io/component	: server
    {{- include "ibmdb2.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create"]