apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ibmdb2.secretName" . }}
  labels:
    app.kubernetes.io/component	: server
    {{- include "ibmdb2.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.db2.password | b64enc | quote }}
