apiVersion: v1
kind: Service
metadata:
  name: {{ include "ibmdb2.fullname" . }}-server
  labels:
    app.kubernetes.io/component	: server
    {{- include "ibmdb2.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/component	: server
    {{- include "ibmdb2.labels" . | nindent 4 }}
  type: NodePort
  ports:
    - port: 50000
      targetPort: 50000
      nodePort: {{ .Values.db2.port }}