apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "rocker.fullname" . }}-pvc-config
  labels:
    app.kubernetes.io/component	: server
    {{- include "rocker.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{.Values.rocker.storage.config}}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "rocker.fullname" . }}-pvc-workspace
  labels:
    app.kubernetes.io/component	: server
    {{- include "rocker.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{.Values.rocker.storage.workspace}}