apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-r-server-config
  namespace: r
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-r-server-workspace
  namespace: r
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi