apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rocker.secretName" . }}
  labels:
    app.kubernetes.io/component	: server
    {{- include "rocker.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.rocker.password | b64enc | quote }}