apiVersion: v1
kind: Service
metadata:
  name: {{ include "rocker.fullname" . }}-server
  labels:
    app.kubernetes.io/component	: server
    {{- include "rocker.labels" . | nindent 4 }}
spec:
  ports:
   - name: http
     protocol: TCP
     port: 8787
  selector:
    app.kubernetes.io/component	: server
    {{- include "rocker.labels" . | nindent 4 }}