# Set the prefix used for all resources in the Helm chart. If not set,
# the prefix will be `<helm release name>`.
name: null

# Override name
nameOverride: null

# Full name override
fullnameOverride: null

# RServer configuration
rocker:
  # password to access server
  password: rocker
  # Storage configuration
  storage:
    # Storage size for config
    config: 1Gi
    # Storage size for workspace
    workspace: 2Gi

# Details of the container image
image:
  repository: rocker/tidyverse
  tag: "4.3.1"
  pullPolicy: IfNotPresent
  # One or more secrets to be used when pulling images
  imagePullSecrets: []
  # - registrySecretName

# Ingress configuration
ingress:
  # Fully qualified domain name of a network host.
  host: null
  # Path is matched against the path of an incoming request.
  path: /
  # Determines the interpretation of the Path matching
  pathType: ImplementationSpecific
  # The name of an IngressClass cluster resource.
  ingressClassName: traefik
  # TLS configuration
  tls: []
  # Annotations to apply to the ingress.
  annotations: {}
  # If you want a custom path, you can try this example:
  # path: /api(/|$)(.*)
  # annotations:
  #  { nginx.ingress.kubernetes.io/rewrite-target: /$2 }

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 300Mi
  # requests:
  #   cpu: 100m
  #   memory: 300Mi

# Node selector to use for the KubeHome deployment. Optional.
nodeSelector: {}