apiVersion: v1
kind: Service
metadata:
  name: {{ include "kuber.fullname" . }}-ui
  labels:
    app.kubernetes.io/component	: ui
    {{- include "kuber.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/component	: ui
    {{- include "kuber.labels" . | nindent 4 }}
  type: ClusterIP
  ports:
  - port: 80