apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubehome.fullname" $ }}-config
  labels:
    app.kubernetes.io/component	: homepage
    {{- include "kubehome.labels" . | nindent 4 }}
data:
  config.json: |
{{ index .Values "kube-home" "config" | indent 4 }}