apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubehome.fullname" $ }}-config
  labels:
    app.kubernetes.io/component	: homepage
    {{- include "kubehome.labels" . | nindent 4 }}
data:
  locale.json: |
{{ .Values.config.locale | indent 4 }}
  apps.json: |
{{ .Values.config.apps | indent 4 }}
  cluster.json: |
{{ .Values.config.cluster | indent 4 }}