apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubehome.fullname" . }}-homepage
  labels:
    app.kubernetes.io/component	: homepage
    {{- include "kubehome.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component	: homepage
      {{- include "kubehome.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component	: homepage
        {{- include "kubehome.labels" . | nindent 8 }}
    spec:
    {{- if .Values.image.imagePullSecrets }}
      imagePullSecrets:
      {{- range .Values.image.imagePullSecrets }}
        - name: {{ . }}
      {{- end }}
    {{- end }}
      volumes:
        - name: json-content
          projected:
            sources:
            - configMap:
              name: {{ include "kubehome.fullname" $ }}-app-config
            - configMap:
              name: {{ include "kubehome.fullname" $ }}-cluster-config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: kube-home
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        volumeMounts:
          - mountPath: /usr/share/nginx/html/content
            name: json-content
        ports:
        - containerPort: 80
        {{- with .Values.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}