apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubehome.fullname" . }}-homepage
  labels:
    app.kubernetes.io/component	: homepage
    {{- include "kubehome.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component	: homepage
      {{- include "kubehome.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component	: homepage
        {{- include "kubehome.labels" . | nindent 8 }}
    spec:
    {{- if .Values.image.imagePullSecrets }}
      imagePullSecrets:
      {{- range .Values.image.imagePullSecrets }}
        - name: {{ . }}
      {{- end }}
    {{- end }}
      volumes:
      - name: json-content
        configMap:
          name: {{ include "kubehome.fullname" $ }}-config
          items: 
          - key: logo.json
            path: "logo.json"
          - key: locale.json
            path: "locale.json"
          - key: apps.json
            path: "apps.json"
          - key: cluster.json
            path: "cluster.json"
      {{- if .Values.config.favicon}}
      - name: cm-favicon
        configMap:
          name: {{.Values.config.favicon}}
      {{- end}}
      {{- if .Values.config.img}}
      - name: cm-img
        configMap:
          name: {{.Values.config.img}}
      {{- end}}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: kube-home
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        volumeMounts:
          - mountPath: /usr/share/nginx/html/content
            name: json-content
          {{- if .Values.config.favicon }}
          - mountPath: /usr/share/nginx/html/favicon.ico
            name: cm-favicon
            subPath: favicon.ico
          {{- end}}
          {{- if .Values.config.img }}
          - mountPath: /usr/share/nginx/html/img
            name: cm-img
          {{- end}}
        ports:
        - containerPort: 80
        {{- with .Values.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}