apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubehome.fullname" . }}-homepage
  labels:
    app.kubernetes.io/component	: homepage
    {{- include "kubehome.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component	: homepage
      {{- include "kubehome.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component	: homepage
        {{- include "kubehome.labels" . | nindent 8 }}
    spec:
    {{- if .Values.image.imagePullSecrets }}
      imagePullSecrets:
      {{- range .Values.image.imagePullSecrets }}
        - name: {{ . }}
      {{- end }}
    {{- end }}
      volumes:
      - name: json-config
        configMap:
          name: {{ include "kubehome.fullname" $ }}-config
      {{- if index .Values "kube-home" "favicon"}}
      - name: cm-favicon
        configMap:
          name: {{index .Values "kube-home" "favicon"}}
      {{- end}}
      {{- if index .Values "kube-home" "img"}}
      - name: cm-img
        configMap:
          name: {{index .Values "kube-home" "img"}}
      {{- end}}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: kube-home
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        volumeMounts:
          - mountPath: /usr/share/nginx/html/config.json
            name: json-config
            subPath: config.json
          {{- if index .Values "kube-home" "favicon" }}
          - mountPath: /usr/share/nginx/html/favicon.ico
            name: cm-favicon
            subPath: favicon.ico
          {{- end}}
          {{- if index .Values "kube-home" "img" }}
          - mountPath: /usr/share/nginx/html/img
            name: cm-img
          {{- end}}
        ports:
        - containerPort: 80
        {{- with .Values.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}