apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubehome.fullname" . }}-homepage
  labels:
    app.kubernetes.io/component	: homepage
    {{- include "kubehome.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/component	: homepage
    {{- include "kubehome.labels" . | nindent 4 }}
  type: ClusterIP
  ports:
  - port: 80